site:
  title: "Batista Apascentar"
  description: "Bem vindo a Apascentar"
personal:
  name: "Batista Apascentar"
  avatar: "https://yt3.googleusercontent.com/D6ZAmm9lMlRI7g5iQbmrffFxd8fk6YxUP_ABKgdvBA6PR4j4wOVcxARdAMJMymrG1q1Ut6hOpQ=s176-c-k-c0x00ffffff-no-rj"
  socialNetworks:
    youtube: "https://www.youtube.com/@IBBJTV"
    github: "https://www.youtube.com/@IBBJTV"
    twitter: "https://www.youtube.com/@IBBJTV"
    linkedin: "https://www.youtube.com/@IBBJTV"
